// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import SmileOutlined from '/root/security-chat-bot/frontend/myapp/node_modules/@ant-design/icons/es/icons/SmileOutlined';
import CrownOutlined from '/root/security-chat-bot/frontend/myapp/node_modules/@ant-design/icons/es/icons/CrownOutlined';
import TableOutlined from '/root/security-chat-bot/frontend/myapp/node_modules/@ant-design/icons/es/icons/TableOutlined';
export default { SmileOutlined, CrownOutlined, TableOutlined };
